FROM ubuntu:25.04
USER root

RUN mkdir /opt/app
RUN chown -R :1000 /opt/app
RUN chmod -R 777 /opt/app

# Libraries for dev
RUN apt-get update && apt-get install -y net-tools zip ripgrep tmux xclip curl git

# Neovim
RUN curl -LO https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-arm64.tar.gz
RUN rm -rf /opt/nvim
RUN tar -C /opt -xzf nvim-linux-arm64.tar.gz
RUN chown -R :users /opt/nvim-linux-arm64
RUN chmod -R 775 /opt/nvim-linux-arm64/

# User specifics
ARG DOCKER_USER=root
RUN useradd -m $DOCKER_USER
USER $DOCKER_USER
ENV PATH="$PATH:/opt/nvim-linux-arm64/bin"
ENV TEMR=xterm-256color

# App specific

# Pyenv and python
RUN git clone --depth=1 https://github.com/pyenv/pyenv.git .pyenv
ENV PYENV_ROOT="${HOME}/.pyenv"
ENV PATH="${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"

ENV PYTHON_VERSION=3.12
RUN pyenv install ${PYTHON_VERSION}
RUN pyenv global ${PYTHON_VERSION}
RUN pip install -r requirements.txt


