FROM ubuntu:25.04
USER root

RUN mkdir /opt/app
RUN chown -R :1000 /opt/app
RUN chmod -R 777 /opt/app

# Libraries for dev
RUN apt-get update && apt-get install -y net-tools zip ripgrep tmux xclip curl git

# Install nvm and node
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION v24.6.0
RUN mkdir -p /usr/local/nvm && apt-get update && echo "y" | apt-get install curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"
ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/bin
ENV PATH="$NODE_PATH:$PATH"
RUN npm install turbo --global

# Neovim
RUN curl -LO https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-arm64.tar.gz
RUN rm -rf /opt/nvim
RUN tar -C /opt -xzf nvim-linux-arm64.tar.gz
RUN chown -R :users /opt/nvim-linux-arm64
RUN chmod -R 775 /opt/nvim-linux-arm64/

# User specifics
ARG DOCKER_USER=root
RUN useradd -m $DOCKER_USER
USER $DOCKER_USER
ENV PATH="$PATH:/opt/nvim-linux-arm64/bin"
ENV TEMR=xterm-256color

# App specific


