#!/bin/bash

USER_ID=$(id -u)
GROUP_ID=$(id -g)
USERNAME=$(id -u -n)

FAKE_ETC="/home/${USERNAME}/fake_etc"

if [[ ! -d "${FAKE_ETC}" ]]
then
	mkdir -p "${FAKE_ETC}"
fi

echo "users:x:${GROUP_ID}:${USER}" > "${FAKE_ETC}"/group
echo "${USER}:x:${USER_ID}:${GROUP_ID}:${USER}:${HOME}:/bin/bash" > "${FAKE_ETC}"/passwd

devcontainer build --workspace-folder .
